# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DCFCalculator.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 982)
        MainWindow.setStyleSheet("background-color: rgb(91, 155, 213);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 5, 600, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 45, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_2.setObjectName("label_2")
        self.label_RepaymentPeriod = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod.setGeometry(QtCore.QRect(320, 25, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod.setFont(font)
        self.label_RepaymentPeriod.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod.setObjectName("label_RepaymentPeriod")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 65, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_CurrentDebtPreceding = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CurrentDebtPreceding.setGeometry(QtCore.QRect(210, 45, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CurrentDebtPreceding.setFont(font)
        self.lineEdit_CurrentDebtPreceding.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_CurrentDebtPreceding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CurrentDebtPreceding.setObjectName("lineEdit_CurrentDebtPreceding")
        self.lineEdit_LongTermDebtPreceding = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_LongTermDebtPreceding.setGeometry(QtCore.QRect(520, 45, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_LongTermDebtPreceding.setFont(font)
        self.lineEdit_LongTermDebtPreceding.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_LongTermDebtPreceding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_LongTermDebtPreceding.setObjectName("lineEdit_LongTermDebtPreceding")
        self.label_RepaymentPeriod_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_2.setGeometry(QtCore.QRect(320, 120, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_2.setFont(font)
        self.label_RepaymentPeriod_2.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_2.setObjectName("label_RepaymentPeriod_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_3.setObjectName("label_3")
        self.lineEdit_RiskFreeRate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_RiskFreeRate.setGeometry(QtCore.QRect(520, 140, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_RiskFreeRate.setFont(font)
        self.lineEdit_RiskFreeRate.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_RiskFreeRate.setText("")
        self.lineEdit_RiskFreeRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_RiskFreeRate.setObjectName("lineEdit_RiskFreeRate")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_MarketRiskPremium = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_MarketRiskPremium.setGeometry(QtCore.QRect(520, 120, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_MarketRiskPremium.setFont(font)
        self.lineEdit_MarketRiskPremium.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_MarketRiskPremium.setText("")
        self.lineEdit_MarketRiskPremium.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_MarketRiskPremium.setObjectName("lineEdit_MarketRiskPremium")
        self.lineEdit_Beta = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Beta.setGeometry(QtCore.QRect(210, 140, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_Beta.setFont(font)
        self.lineEdit_Beta.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_Beta.setText("")
        self.lineEdit_Beta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Beta.setObjectName("lineEdit_Beta")
        self.lineEdit_CostOfEquity = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CostOfEquity.setGeometry(QtCore.QRect(210, 160, 400, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CostOfEquity.setFont(font)
        self.lineEdit_CostOfEquity.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_CostOfEquity.setText("")
        self.lineEdit_CostOfEquity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CostOfEquity.setObjectName("lineEdit_CostOfEquity")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(320, 140, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 100, 600, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_RepaymentPeriod_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_3.setGeometry(QtCore.QRect(320, 195, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_3.setFont(font)
        self.label_RepaymentPeriod_3.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_3.setObjectName("label_RepaymentPeriod_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 175, 600, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_NumberOfOutstandingShares = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_NumberOfOutstandingShares.setGeometry(QtCore.QRect(520, 195, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_NumberOfOutstandingShares.setFont(font)
        self.lineEdit_NumberOfOutstandingShares.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_NumberOfOutstandingShares.setText("")
        self.lineEdit_NumberOfOutstandingShares.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_NumberOfOutstandingShares.setObjectName("lineEdit_NumberOfOutstandingShares")
        self.lineEdit_WeightedAverageCostOfCapital = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_WeightedAverageCostOfCapital.setGeometry(QtCore.QRect(210, 235, 400, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_WeightedAverageCostOfCapital.setFont(font)
        self.lineEdit_WeightedAverageCostOfCapital.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_WeightedAverageCostOfCapital.setText("")
        self.lineEdit_WeightedAverageCostOfCapital.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_WeightedAverageCostOfCapital.setObjectName("lineEdit_WeightedAverageCostOfCapital")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 195, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_11.setObjectName("label_11")
        self.lineEdit_Debt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Debt.setGeometry(QtCore.QRect(210, 195, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_Debt.setFont(font)
        self.lineEdit_Debt.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_Debt.setText("")
        self.lineEdit_Debt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_Debt.setObjectName("lineEdit_Debt")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 235, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_12.setObjectName("label_12")
        self.lineEdit_CashFlow1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CashFlow1.setGeometry(QtCore.QRect(210, 270, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CashFlow1.setFont(font)
        self.lineEdit_CashFlow1.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_CashFlow1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CashFlow1.setObjectName("lineEdit_CashFlow1")
        self.lineEdit_CashFlow2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CashFlow2.setGeometry(QtCore.QRect(210, 290, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_CashFlow2.setFont(font)
        self.lineEdit_CashFlow2.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_CashFlow2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CashFlow2.setObjectName("lineEdit_CashFlow2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 270, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_13.setObjectName("label_13")
        self.label_RepaymentPeriod_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_4.setGeometry(QtCore.QRect(10, 290, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_4.setFont(font)
        self.label_RepaymentPeriod_4.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_4.setObjectName("label_RepaymentPeriod_4")
        self.lineEdit_CashFlow3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CashFlow3.setGeometry(QtCore.QRect(210, 310, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CashFlow3.setFont(font)
        self.lineEdit_CashFlow3.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_CashFlow3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CashFlow3.setObjectName("lineEdit_CashFlow3")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 250, 600, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(10, 310, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 330, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_16.setObjectName("label_16")
        self.lineEdit_CashFlowCalculator = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CashFlowCalculator.setGeometry(QtCore.QRect(210, 330, 400, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CashFlowCalculator.setFont(font)
        self.lineEdit_CashFlowCalculator.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_CashFlowCalculator.setText("")
        self.lineEdit_CashFlowCalculator.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CashFlowCalculator.setObjectName("lineEdit_CashFlowCalculator")
        self.lineEdit_CashFlow4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CashFlow4.setGeometry(QtCore.QRect(520, 270, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CashFlow4.setFont(font)
        self.lineEdit_CashFlow4.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_CashFlow4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CashFlow4.setObjectName("lineEdit_CashFlow4")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(320, 270, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_17.setObjectName("label_17")
        self.lineEdit_CashFlow5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CashFlow5.setGeometry(QtCore.QRect(520, 290, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_CashFlow5.setFont(font)
        self.lineEdit_CashFlow5.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_CashFlow5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CashFlow5.setObjectName("lineEdit_CashFlow5")
        self.label_RepaymentPeriod_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_5.setGeometry(QtCore.QRect(320, 290, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_5.setFont(font)
        self.label_RepaymentPeriod_5.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_5.setObjectName("label_RepaymentPeriod_5")
        self.lineEdit_CurrentStockPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CurrentStockPrice.setGeometry(QtCore.QRect(520, 215, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_CurrentStockPrice.setFont(font)
        self.lineEdit_CurrentStockPrice.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_CurrentStockPrice.setText("")
        self.lineEdit_CurrentStockPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CurrentStockPrice.setObjectName("lineEdit_CurrentStockPrice")
        self.label_RepaymentPeriod_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_8.setGeometry(QtCore.QRect(320, 215, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_8.setFont(font)
        self.label_RepaymentPeriod_8.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_8.setObjectName("label_RepaymentPeriod_8")
        self.lineEdit_GrowthRateOfCompany = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_GrowthRateOfCompany.setGeometry(QtCore.QRect(520, 310, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_GrowthRateOfCompany.setFont(font)
        self.lineEdit_GrowthRateOfCompany.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_GrowthRateOfCompany.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_GrowthRateOfCompany.setObjectName("lineEdit_GrowthRateOfCompany")
        self.label_RepaymentPeriod_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_9.setGeometry(QtCore.QRect(320, 310, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_9.setFont(font)
        self.label_RepaymentPeriod_9.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_9.setObjectName("label_RepaymentPeriod_9")
        self.lineEdit_LongTermGrowth = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_LongTermGrowth.setGeometry(QtCore.QRect(210, 370, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_LongTermGrowth.setFont(font)
        self.lineEdit_LongTermGrowth.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_LongTermGrowth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_LongTermGrowth.setObjectName("lineEdit_LongTermGrowth")
        self.lineEdit_WACC_fromAbove = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_WACC_fromAbove.setGeometry(QtCore.QRect(210, 390, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_WACC_fromAbove.setFont(font)
        self.lineEdit_WACC_fromAbove.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_WACC_fromAbove.setText("")
        self.lineEdit_WACC_fromAbove.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_WACC_fromAbove.setObjectName("lineEdit_WACC_fromAbove")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(10, 370, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_21.setObjectName("label_21")
        self.label_RepaymentPeriod_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_10.setGeometry(QtCore.QRect(10, 390, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_10.setFont(font)
        self.label_RepaymentPeriod_10.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_10.setObjectName("label_RepaymentPeriod_10")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 350, 600, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(10, 410, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_22.setObjectName("label_22")
        self.lineEdit_TerminalValue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_TerminalValue.setGeometry(QtCore.QRect(210, 410, 400, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_TerminalValue.setFont(font)
        self.lineEdit_TerminalValue.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_TerminalValue.setText("")
        self.lineEdit_TerminalValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_TerminalValue.setObjectName("lineEdit_TerminalValue")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 430, 600, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(10, 450, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(10, 470, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_25.setObjectName("label_25")
        self.label_RepaymentPeriod_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_13.setGeometry(QtCore.QRect(320, 450, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_13.setFont(font)
        self.label_RepaymentPeriod_13.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_13.setObjectName("label_RepaymentPeriod_13")
        self.lineEdit_SumOfPVOfFCFS = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_SumOfPVOfFCFS.setGeometry(QtCore.QRect(520, 450, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_SumOfPVOfFCFS.setFont(font)
        self.lineEdit_SumOfPVOfFCFS.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_SumOfPVOfFCFS.setText("")
        self.lineEdit_SumOfPVOfFCFS.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_SumOfPVOfFCFS.setObjectName("lineEdit_SumOfPVOfFCFS")
        self.lineEdit_PVOfTerminalValue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_PVOfTerminalValue.setGeometry(QtCore.QRect(210, 450, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_PVOfTerminalValue.setFont(font)
        self.lineEdit_PVOfTerminalValue.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_PVOfTerminalValue.setText("")
        self.lineEdit_PVOfTerminalValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_PVOfTerminalValue.setObjectName("lineEdit_PVOfTerminalValue")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 610, 600, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_EnterpriseValue = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EnterpriseValue.setGeometry(QtCore.QRect(210, 470, 400, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_EnterpriseValue.setFont(font)
        self.lineEdit_EnterpriseValue.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_EnterpriseValue.setText("")
        self.lineEdit_EnterpriseValue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_EnterpriseValue.setObjectName("lineEdit_EnterpriseValue")
        self.lineEdit_LongTermDebtLatest = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_LongTermDebtLatest.setGeometry(QtCore.QRect(520, 25, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_LongTermDebtLatest.setFont(font)
        self.lineEdit_LongTermDebtLatest.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_LongTermDebtLatest.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_LongTermDebtLatest.setObjectName("lineEdit_LongTermDebtLatest")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(10, 25, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_26.setObjectName("label_26")
        self.lineEdit_CurrentDebtLastest = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CurrentDebtLastest.setGeometry(QtCore.QRect(210, 25, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CurrentDebtLastest.setFont(font)
        self.lineEdit_CurrentDebtLastest.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_CurrentDebtLastest.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CurrentDebtLastest.setObjectName("lineEdit_CurrentDebtLastest")
        self.lineEdit_InterestExpense = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_InterestExpense.setGeometry(QtCore.QRect(210, 65, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_InterestExpense.setFont(font)
        self.lineEdit_InterestExpense.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_InterestExpense.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_InterestExpense.setObjectName("lineEdit_InterestExpense")
        self.label_RepaymentPeriod_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_14.setGeometry(QtCore.QRect(320, 45, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_14.setFont(font)
        self.label_RepaymentPeriod_14.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_14.setObjectName("label_RepaymentPeriod_14")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(10, 85, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_27.setObjectName("label_27")
        self.lineEdit_CostOfDebt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CostOfDebt.setGeometry(QtCore.QRect(210, 85, 400, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CostOfDebt.setFont(font)
        self.lineEdit_CostOfDebt.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_CostOfDebt.setText("")
        self.lineEdit_CostOfDebt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CostOfDebt.setObjectName("lineEdit_CostOfDebt")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(10, 215, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_28.setObjectName("label_28")
        self.lineEdit_CorporateTaxRate = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CorporateTaxRate.setGeometry(QtCore.QRect(210, 215, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_CorporateTaxRate.setFont(font)
        self.lineEdit_CorporateTaxRate.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_CorporateTaxRate.setText("")
        self.lineEdit_CorporateTaxRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CorporateTaxRate.setObjectName("lineEdit_CorporateTaxRate")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(10, 120, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_30.setObjectName("label_30")
        self.lineEdit_StockTicker = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_StockTicker.setGeometry(QtCore.QRect(210, 120, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_StockTicker.setFont(font)
        self.lineEdit_StockTicker.setStyleSheet("background-color:rgb(255,255,255);")
        self.lineEdit_StockTicker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_StockTicker.setObjectName("lineEdit_StockTicker")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(10, 490, 600, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.lineEdit_EstimatedSharePrice = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EstimatedSharePrice.setGeometry(QtCore.QRect(210, 550, 400, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_EstimatedSharePrice.setFont(font)
        self.lineEdit_EstimatedSharePrice.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_EstimatedSharePrice.setText("")
        self.lineEdit_EstimatedSharePrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_EstimatedSharePrice.setObjectName("lineEdit_EstimatedSharePrice")
        self.lineEdit_NoOfOrdinarySharesOutstanding = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_NoOfOrdinarySharesOutstanding.setGeometry(QtCore.QRect(520, 510, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_NoOfOrdinarySharesOutstanding.setFont(font)
        self.lineEdit_NoOfOrdinarySharesOutstanding.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_NoOfOrdinarySharesOutstanding.setText("")
        self.lineEdit_NoOfOrdinarySharesOutstanding.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_NoOfOrdinarySharesOutstanding.setObjectName("lineEdit_NoOfOrdinarySharesOutstanding")
        self.label_RepaymentPeriod_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_12.setGeometry(QtCore.QRect(320, 510, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_12.setFont(font)
        self.label_RepaymentPeriod_12.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_12.setObjectName("label_RepaymentPeriod_12")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(10, 550, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_29.setObjectName("label_29")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(10, 510, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_31.setObjectName("label_31")
        self.lineEdit_CurrentYearDebt = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CurrentYearDebt.setGeometry(QtCore.QRect(210, 530, 90, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_CurrentYearDebt.setFont(font)
        self.lineEdit_CurrentYearDebt.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_CurrentYearDebt.setText("")
        self.lineEdit_CurrentYearDebt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CurrentYearDebt.setObjectName("lineEdit_CurrentYearDebt")
        self.label_RepaymentPeriod_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_15.setGeometry(QtCore.QRect(10, 530, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_15.setFont(font)
        self.label_RepaymentPeriod_15.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_15.setObjectName("label_RepaymentPeriod_15")
        self.lineEdit_EnterpriseValue_fromAbove = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EnterpriseValue_fromAbove.setGeometry(QtCore.QRect(210, 510, 90, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_EnterpriseValue_fromAbove.setFont(font)
        self.lineEdit_EnterpriseValue_fromAbove.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_EnterpriseValue_fromAbove.setText("")
        self.lineEdit_EnterpriseValue_fromAbove.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_EnterpriseValue_fromAbove.setObjectName("lineEdit_EnterpriseValue_fromAbove")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(10, 570, 600, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.lineEdit_CurrentSharePrice = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_CurrentSharePrice.setGeometry(QtCore.QRect(210, 590, 75, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_CurrentSharePrice.setFont(font)
        self.lineEdit_CurrentSharePrice.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_CurrentSharePrice.setText("")
        self.lineEdit_CurrentSharePrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_CurrentSharePrice.setObjectName("lineEdit_CurrentSharePrice")
        self.label_RepaymentPeriod_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_16.setGeometry(QtCore.QRect(10, 590, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_16.setFont(font)
        self.label_RepaymentPeriod_16.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_16.setObjectName("label_RepaymentPeriod_16")
        self.lineEdit_EstimatedSharePrice_fromAbove = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_EstimatedSharePrice_fromAbove.setGeometry(QtCore.QRect(535, 590, 75, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lineEdit_EstimatedSharePrice_fromAbove.setFont(font)
        self.lineEdit_EstimatedSharePrice_fromAbove.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_EstimatedSharePrice_fromAbove.setText("")
        self.lineEdit_EstimatedSharePrice_fromAbove.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_EstimatedSharePrice_fromAbove.setObjectName("lineEdit_EstimatedSharePrice_fromAbove")
        self.label_RepaymentPeriod_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_17.setGeometry(QtCore.QRect(335, 590, 190, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_17.setFont(font)
        self.label_RepaymentPeriod_17.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_17.setObjectName("label_RepaymentPeriod_17")
        self.lineEdit_Result = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_Result.setGeometry(QtCore.QRect(10, 645, 600, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.lineEdit_Result.setFont(font)
        self.lineEdit_Result.setStyleSheet("background-color:rgb(244,244,121);")
        self.lineEdit_Result.setText("")
        self.lineEdit_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_Result.setObjectName("lineEdit_Result")
        self.label_RepaymentPeriod_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_RepaymentPeriod_18.setGeometry(QtCore.QRect(300, 590, 20, 15))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.label_RepaymentPeriod_18.setFont(font)
        self.label_RepaymentPeriod_18.setStyleSheet("color: rgb(255,255,255); border:1px solid rgb(65,113,156);")
        self.label_RepaymentPeriod_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_RepaymentPeriod_18.setObjectName("label_RepaymentPeriod_18")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Discounted Cash Flow Calculator"))
        self.label.setText(_translate("MainWindow", "Cost of Debt Calculator"))
        self.label_2.setText(_translate("MainWindow", "Current Debt (Preceding FY-End) (S$)"))
        self.label_RepaymentPeriod.setText(_translate("MainWindow", "Long Term Debt (Latest FY-End) (S$)"))
        self.label_4.setText(_translate("MainWindow", "Interest Expense (Latest FY-End) (S$)"))
        self.lineEdit_CurrentDebtPreceding.setText(_translate("MainWindow", "33428000000"))
        self.lineEdit_LongTermDebtPreceding.setText(_translate("MainWindow", "62643000000"))
        self.label_RepaymentPeriod_2.setText(_translate("MainWindow", "Market Risk Premium (%)"))
        self.label_3.setText(_translate("MainWindow", "Beta"))
        self.label_6.setText(_translate("MainWindow", "Cost of Equity (%)"))
        self.label_7.setText(_translate("MainWindow", "Risk Free Rate (%)"))
        self.label_8.setText(_translate("MainWindow", "Cost of Equity Calculator"))
        self.label_RepaymentPeriod_3.setText(_translate("MainWindow", "Number of Outstanding Shares"))
        self.label_9.setText(_translate("MainWindow", "WACC Calculator"))
        self.label_11.setText(_translate("MainWindow", "Debt (S$)"))
        self.label_12.setText(_translate("MainWindow", "Weighted Average Cost of Capital"))
        self.lineEdit_CashFlow1.setText(_translate("MainWindow", "16958000000"))
        self.lineEdit_CashFlow2.setText(_translate("MainWindow", "0"))
        self.label_13.setText(_translate("MainWindow", "Cash Flow (Year 1) (S$)"))
        self.label_RepaymentPeriod_4.setText(_translate("MainWindow", "Cash Flow (Year 2) (S$)"))
        self.lineEdit_CashFlow3.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Cash Flow Calculator"))
        self.label_15.setText(_translate("MainWindow", "Cash Flow (Year 3) (S$)"))
        self.label_16.setText(_translate("MainWindow", "Cash Flow Calculator (S$)"))
        self.lineEdit_CashFlow4.setText(_translate("MainWindow", "0"))
        self.label_17.setText(_translate("MainWindow", "Cash Flow (Year 4) (S$)"))
        self.lineEdit_CashFlow5.setText(_translate("MainWindow", "0"))
        self.label_RepaymentPeriod_5.setText(_translate("MainWindow", "Cash Flow (Year 5) (S$)"))
        self.label_RepaymentPeriod_8.setText(_translate("MainWindow", "Market Capitalisation"))
        self.lineEdit_GrowthRateOfCompany.setText(_translate("MainWindow", "5"))
        self.label_RepaymentPeriod_9.setText(_translate("MainWindow", "Growth Rate of Company (%)"))
        self.lineEdit_LongTermGrowth.setText(_translate("MainWindow", "2"))
        self.label_21.setText(_translate("MainWindow", "Long Term Growth Rate (%)"))
        self.label_RepaymentPeriod_10.setText(_translate("MainWindow", "WACC (%)"))
        self.label_10.setText(_translate("MainWindow", "Terminal Value Calculator"))
        self.label_22.setText(_translate("MainWindow", "Terminal Value (S$)"))
        self.label_23.setText(_translate("MainWindow", "Enterprise Value Calculator"))
        self.label_24.setText(_translate("MainWindow", "Present Value of Terminal Value (S$)"))
        self.label_25.setText(_translate("MainWindow", "Enterprise Value (S$)"))
        self.label_RepaymentPeriod_13.setText(_translate("MainWindow", "Sum of PV of FCFS (S$)"))
        self.pushButton_6.setText(_translate("MainWindow", "Calculate"))
        self.lineEdit_LongTermDebtLatest.setText(_translate("MainWindow", "62802000000"))
        self.label_26.setText(_translate("MainWindow", "Current Debt (Latest FY-End) (S$)"))
        self.lineEdit_CurrentDebtLastest.setText(_translate("MainWindow", "36275000000"))
        self.lineEdit_InterestExpense.setText(_translate("MainWindow", "630000000"))
        self.label_RepaymentPeriod_14.setText(_translate("MainWindow", "Long Term Debt (Preceding FY-end) (S$)"))
        self.label_27.setText(_translate("MainWindow", "Cost of Debt (%)"))
        self.label_28.setText(_translate("MainWindow", "Corporate Tax Rate (%)"))
        self.label_30.setText(_translate("MainWindow", "Stock Ticker"))
        self.lineEdit_StockTicker.setText(_translate("MainWindow", "IBM"))
        self.label_18.setText(_translate("MainWindow", "Estimated Share Price Calculator"))
        self.label_RepaymentPeriod_12.setText(_translate("MainWindow", "No. of Ordinary Shares Outstanding"))
        self.label_29.setText(_translate("MainWindow", "Estimated Share Price (S$)"))
        self.label_31.setText(_translate("MainWindow", "Enterprise Value (S$)"))
        self.label_RepaymentPeriod_15.setText(_translate("MainWindow", "Current Year Debt (S$)"))
        self.label_19.setText(_translate("MainWindow", "Results"))
        self.label_RepaymentPeriod_16.setText(_translate("MainWindow", "Current Share Price (S$)"))
        self.label_RepaymentPeriod_17.setText(_translate("MainWindow", "Estimated Share Price (S$)"))
        self.label_RepaymentPeriod_18.setText(_translate("MainWindow", "VS"))

